# Generated by Django 3.0.2 on 2020-01-14 22:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_title', models.TextField(help_text='Program Title')),
                ('program_number', models.CharField(help_text='Program Number', max_length=6)),
                ('popular_name', models.TextField(help_text='Popular Name (020)')),
                ('federal_agency', models.TextField(help_text='Federal Agency (030)')),
                ('authorization', django.contrib.postgres.fields.jsonb.JSONField(help_text='Authorization (040)')),
                ('objectives', models.TextField(help_text='Objectives (050)')),
                ('assistance_types', models.TextField(help_text='Types of Assistance (060)')),
                ('uses_restrictions', models.TextField(help_text='Uses and Use Restrictions (070)')),
                ('applicant_eligibility', models.TextField(help_text='Applicant Eligibility (081)')),
                ('beneficiary_eligibility', models.TextField(help_text='Beneficiary Eligibility (082)')),
                ('credentials_documentation', django.contrib.postgres.fields.jsonb.JSONField(help_text='Credentials/Documentation (083)')),
                ('preapplication_coordination', django.contrib.postgres.fields.jsonb.JSONField(help_text='Preapplication Coordination (091)')),
                ('application_procedures', django.contrib.postgres.fields.jsonb.JSONField(help_text='Application Procedures (092)')),
                ('award_procedure', models.TextField(help_text='Award Procedure (093)')),
                ('deadlines', django.contrib.postgres.fields.jsonb.JSONField(help_text='Deadlines (094)')),
                ('approval_time', models.TextField(help_text='Range of Approval/Disapproval Time (095)')),
                ('appeals', models.TextField(help_text='Appeals (096)')),
                ('renewals', models.TextField(help_text='Renewals (097)')),
                ('requirements', django.contrib.postgres.fields.jsonb.JSONField(help_text='Formula and Matching Requirements (101)')),
                ('assistance_period', django.contrib.postgres.fields.jsonb.JSONField(help_text='Length and Time Phasing of Assistance (102)', null=True)),
                ('reports', django.contrib.postgres.fields.jsonb.JSONField(help_text='Reports (111)')),
                ('audits', django.contrib.postgres.fields.jsonb.JSONField(help_text='Audits (112)')),
                ('records', models.TextField(help_text='Records (113)')),
                ('account_identification', models.TextField(help_text='Account Identification (121)')),
                ('obligations', models.TextField(help_text='Obligations (122)')),
                ('assistance_range', models.TextField(help_text='Range and Average of Financial Assistance (123)')),
                ('program_accomplishments', django.contrib.postgres.fields.jsonb.JSONField(help_text='Program Accomplishments (130)')),
                ('regulations', models.TextField(help_text='Regulations, Guidelines, and Literature (140)')),
                ('regional_local_office', django.contrib.postgres.fields.jsonb.JSONField(help_text='Regional or Local Office (151)')),
                ('headquarters_office', models.TextField(help_text='Headquarters Office (152)')),
                ('website', models.URLField(help_text='Website Address (153)')),
                ('related_programs', models.TextField(help_text='Related Programs (160)')),
                ('funded_project_examples', models.TextField(help_text='Examples of Funded Projects (170)')),
                ('selection_criteria', models.TextField(help_text='Criteria for Selecting Proposals (180)')),
                ('published_date', models.DateField(help_text='Published Date')),
                ('parent_shortname', models.CharField(help_text='Parent Shortname', max_length=8)),
                ('sam_gov_url', models.URLField(help_text='URL')),
                ('recovery', models.BooleanField(help_text='Recovery')),
            ],
        ),
    ]
