# Generated by Django 3.0.2 on 2020-01-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFDA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_year', models.DecimalField(decimal_places=0, help_text='Audit Year and DBKEY (database key) combined make up the primary key.', max_digits=4)),
                ('dbkey', models.CharField(help_text='Audit Year and DBKEY (database key) combined make up the primary key.', max_length=6)),
                ('ein', models.CharField(help_text='Employer Identification Number', max_length=9)),
                ('cfda', models.CharField(help_text='Federal Agency Prefix and Extension', max_length=52)),
                ('award_identification', models.CharField(blank=True, help_text='Other data used to identify the award which is not a CFDA number (e.g., program year, contract number)', max_length=50, null=True)),
                ('r_and_d', models.BooleanField(help_text='Indicate whether or not the program is a Research and Development program', null=True)),
                ('loans', models.BooleanField(help_text='Indicate whether or not the program is a Loan or Loan Guarantee (only available for audit years 2013 and beyond)', null=True)),
                ('loan_balance', models.CharField(blank=True, help_text='The loan or loan guarantee (loan) balance outstanding at the end of the audit period.', max_length=12, null=True)),
                ('arra', models.BooleanField(help_text='American Recovery and Reinvestment Act Funded Program', null=True)),
                ('federal_program_name', models.CharField(blank=True, help_text='Name of Federal Program', max_length=300, null=True)),
                ('amount', models.CharField(blank=True, help_text='Amount Expended for the Federal Program', max_length=12, null=True)),
                ('cluster_name', models.CharField(blank=True, help_text='The name of the cluster', max_length=75, null=True)),
                ('state_cluster_name', models.CharField(blank=True, help_text='The name of the state cluster', max_length=75, null=True)),
                ('program_total', models.CharField(blank=True, help_text='Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same CFDA Prefix and Extension', max_length=12, null=True)),
                ('cluster_total', models.CharField(blank=True, help_text='Total Federal awards expended for each individual Federal program is auto-generated by summing the amount expended for all line items with the same Cluster Name', max_length=12, null=True)),
                ('direct', models.BooleanField(help_text='Indicate whether or not the award was received directly from a Federal awarding agency', null=True)),
                ('pass_through_award', models.BooleanField(help_text='Indicates whether or not funds were passed through to any subrecipients for the Federal program', null=True)),
                ('pass_through_amount', models.CharField(help_text='Amount passed through to subrecipients', max_length=12, null=True)),
                ('major_program', models.BooleanField(help_text='Indicate whether or not the Federal program is a major program', null=True)),
                ('type_report_mp', models.CharField(blank=True, choices=[('U', 'Unqualified'), ('Q', 'Qualified'), ('A', 'Adverse'), ('D', 'Disclaimer')], help_text='Type of Report Issued on the Major Program Compliance', max_length=1, null=True)),
                ('type_requirement', models.CharField(blank=True, help_text='Type Requirement Failure', max_length=256, null=True)),
                ('qcosts2', models.BooleanField(help_text='Indicate whether or not the audit disclosed any known questioned costs.', null=True)),
                ('findings', models.TextField(blank=True, null=True)),
                ('finding_ref_nums', models.CharField(blank=True, help_text='Findings Reference Numbers', max_length=100, null=True)),
                ('findings_count', models.IntegerField(help_text='Number of findings for the federal program (only available for audit years 2013 and beyond)', null=True)),
                ('elec_audits_id', models.IntegerField(help_text='FAC system generated sequence number used to link to Findings data between CFDA Info and Findings')),
                ('other_cluster_name', models.CharField(blank=True, help_text='The name of the cluster (if not listed in the Compliance Supplement)', max_length=75, null=True)),
                ('cfda_program_name', models.CharField(help_text='Name of Federal Program (auto-generated by FAC from the CFDA catalog)', max_length=300)),
            ],
            options={
                'verbose_name': 'CFDA number',
            },
        ),
    ]
