# Generated by Django 3.0.2 on 2020-01-24 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200123_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancelisting',
            name='program_number',
            field=models.CharField(help_text='Program Number', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cfda',
            name='cfda',
            field=models.ForeignKey(db_constraint=False, help_text='Federal Agency Prefix and Extension', on_delete=django.db.models.deletion.DO_NOTHING, to='data.AssistanceListing'),
        ),
    ]
