# Generated by Django 3.0.2 on 2020-01-24 01:49

import compositefk.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200124_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='finding',
            field=compositefk.fields.CompositeForeignKey(default=None, null_if_equal=[], on_delete=django.db.models.deletion.DO_NOTHING, related_name='findings', to='data.Audit', to_fields={'audit_year': compositefk.fields.LocalFieldValue('audit_year'), 'dbkey': compositefk.fields.LocalFieldValue('dbkey')}),
            preserve_default=False,
        ),
    ]
