# Generated by Django 3.0.2 on 2020-01-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_finding_finding'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingText',
            fields=[
                ('seq_number', models.IntegerField(help_text='Order that the findings text was reported', primary_key=True, serialize=False)),
                ('dbkey', models.IntegerField(help_text='Audit Year and DBKEY (database key) combined make up the primary key.')),
                ('audit_year', models.DecimalField(decimal_places=0, help_text='Audit Year and DBKEY (database key) combined make up the primary key.', max_digits=4)),
                ('finding_ref_nums', models.CharField(help_text='Audit Finding Reference Number', max_length=100)),
                ('text', models.TextField(help_text='Content of the finding text')),
                ('charts_tables', models.BooleanField(help_text='Indicates whether or not the text contained charts or tables that could not be entered due to formatting restrictions')),
            ],
        ),
    ]
