# Generated by Django 3.0.2 on 2020-01-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_findingtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancelisting',
            name='assistance_range',
            field=models.TextField(blank=True, help_text='Range and Average of Financial Assistance (123)', null=True),
        ),
        migrations.AlterField(
            model_name='assistancelisting',
            name='funded_project_examples',
            field=models.TextField(blank=True, help_text='Examples of Funded Projects (170)', null=True),
        ),
        migrations.AlterField(
            model_name='assistancelisting',
            name='parent_shortname',
            field=models.CharField(blank=True, help_text='Parent Shortname', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='assistancelisting',
            name='popular_name',
            field=models.TextField(blank=True, help_text='Popular Name (020)', null=True),
        ),
        migrations.AlterField(
            model_name='assistancelisting',
            name='records',
            field=models.TextField(blank=True, help_text='Records (113)', null=True),
        ),
        migrations.AlterField(
            model_name='assistancelisting',
            name='related_programs',
            field=models.TextField(blank=True, help_text='Related Programs (160)', null=True),
        ),
        migrations.AlterField(
            model_name='assistancelisting',
            name='website',
            field=models.URLField(blank=True, help_text='Website Address (153)', null=True),
        ),
    ]
