# Generated by Django 3.0.2 on 2020-01-31 21:53

import compositefk.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20200129_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='finding_text',
            field=compositefk.fields.CompositeForeignKey(default=None, null_if_equal=[], on_delete=django.db.models.deletion.DO_NOTHING, related_name='findings', to='data.FindingText', to_fields={'audit_year': compositefk.fields.LocalFieldValue('audit_year'), 'dbkey': compositefk.fields.LocalFieldValue('dbkey'), 'finding_ref_nums': compositefk.fields.LocalFieldValue('finding_ref_nums')}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='findingtext',
            name='dbkey',
            field=models.CharField(help_text='Audit Year and DBKEY (database key) combined make up the primary key.', max_length=6),
        ),
    ]
