# Generated by Django 3.0.2 on 2020-02-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_findingtext_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPText',
            fields=[
                ('seq_number', models.IntegerField(help_text='Order that the CAP text was reported', primary_key=True, serialize=False)),
                ('dbkey', models.CharField(help_text='Audit Year and DBKEY (database key) combined make up the primary key.', max_length=6)),
                ('audit_year', models.DecimalField(decimal_places=0, help_text='Audit Year and DBKEY (database key) combined make up the primary key.', max_digits=4)),
                ('finding_ref_nums', models.CharField(help_text='Audit Finding Reference Number', max_length=100)),
                ('text', models.TextField(help_text='Content of the Corrective Action Plan (CAP)')),
                ('charts_tables', models.BooleanField(help_text='Indicates whether or not the text contained charts or tables that could not be entered due to formatting restrictions')),
            ],
        ),
    ]
