# Generated by Django 3.0.2 on 2020-02-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_captext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captext',
            options={'verbose_name': 'CAP text', 'verbose_name_plural': 'CAP text'},
        ),
        migrations.AlterModelOptions(
            name='findingtext',
            options={'verbose_name_plural': 'finding text'},
        ),
        migrations.AddIndex(
            model_name='captext',
            index=models.Index(fields=['audit_year', 'dbkey'], name='data_captex_audit_y_cd537b_idx'),
        ),
        migrations.AddIndex(
            model_name='findingtext',
            index=models.Index(fields=['audit_year', 'dbkey'], name='data_findin_audit_y_c2fcb8_idx'),
        ),
    ]
