# Generated by Django 3.0.2 on 2020-02-04 18:39

import compositefk.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20200204_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='captext',
            name='finding_text',
            field=compositefk.fields.CompositeForeignKey(default=None, null_if_equal=[], on_delete=django.db.models.deletion.DO_NOTHING, related_name='cap_texts', to='data.FindingText', to_fields={'audit_year': compositefk.fields.LocalFieldValue('audit_year'), 'dbkey': compositefk.fields.LocalFieldValue('dbkey'), 'finding_ref_nums': compositefk.fields.LocalFieldValue('finding_ref_nums')}),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='captext',
            index=models.Index(fields=['audit_year', 'dbkey', 'finding_ref_nums'], name='data_captex_audit_y_d4a8b2_idx'),
        ),
    ]
