# Generated by Django 3.0.3 on 2020-02-06 00:23

import compositefk.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20200204_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFExtract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_year', models.DecimalField(decimal_places=0, help_text='Audit Year and DBKEY (database key) combined make up the primary key.', max_digits=4)),
                ('dbkey', models.CharField(help_text='Audit Year and DBKEY (database key) combined make up the primary key.', max_length=6)),
                ('finding_ref_nums', models.CharField(blank=True, help_text='Findings Reference Numbers', max_length=100, null=True)),
                ('finding_text', django.contrib.postgres.fields.jsonb.JSONField(help_text='Extracted PDF finding')),
                ('cap_text', django.contrib.postgres.fields.jsonb.JSONField(help_text='Extracted PDF corrective action plan')),
                ('last_updated', models.DateField(help_text='Last Updated')),
                ('audit', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.DO_NOTHING, related_name='pdf_extracts', to='data.Audit', to_fields={'audit_year': compositefk.fields.LocalFieldValue('audit_year'), 'dbkey': compositefk.fields.LocalFieldValue('dbkey')})),
            ],
            options={
                'verbose_name_plural': 'PDF extracts',
            },
        ),
    ]
