# Generated by Django 3.0.3 on 2020-02-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_pdfextract'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pdfextract',
            index=models.Index(fields=['audit_year', 'dbkey'], name='data_pdfext_audit_y_51c28f_idx'),
        ),
    ]
