# Generated by Django 3.0.3 on 2020-02-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_auto_20200211_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='tot_fed_expend',
            field=models.DecimalField(decimal_places=2, help_text='Total Federal Expenditures', max_digits=16),
        ),
    ]
