# Generated by Django 3.0.3 on 2020-02-21 19:20

import compositefk.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20200219_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='cfda',
        ),
        migrations.AddField(
            model_name='captext',
            name='audit',
            field=compositefk.fields.CompositeForeignKey(default=None, null_if_equal=[], on_delete=django.db.models.deletion.DO_NOTHING, related_name='cap_texts', to='data.Audit', to_fields={'audit_year': compositefk.fields.LocalFieldValue('audit_year'), 'dbkey': compositefk.fields.LocalFieldValue('dbkey')}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfda',
            name='audit',
            field=compositefk.fields.CompositeForeignKey(default=None, null_if_equal=[], on_delete=django.db.models.deletion.DO_NOTHING, related_name='cfdas', to='data.Audit', to_fields={'audit_year': compositefk.fields.LocalFieldValue('audit_year'), 'dbkey': compositefk.fields.LocalFieldValue('dbkey')}),
            preserve_default=False,
        ),
    ]
