# Generated by Django 3.0.3 on 2020-02-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20200221_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfda',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount Expended for the Federal Program', max_digits=16, null=True),
        ),
    ]
