# Generated by Django 3.0.3 on 2020-02-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20200221_1952'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['cog_agency'], name='data_audit_cog_age_272f5f_idx'),
        ),
    ]
