# Generated by Django 3.1 on 2020-08-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20200224_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('operation', models.CharField(choices=[('load_table', 'Load table'), ('download_table', 'Download table'), ('fac_crawl', 'FAC document crawl')], max_length=16)),
                ('target', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='audit',
            name='data_audit_cog_age_272f5f_idx',
        ),
    ]
