# Generated by Django 3.1 on 2020-08-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20200812_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancelisting',
            name='application_procedures',
            field=models.JSONField(help_text='Application Procedures (092)'),
        ),
        migrations.AlterField(
            model_name='assistancelisting',
            name='assistance_period',
            field=models.JSONField(help_text='Length and Time Phasing of Assistance (102)', null=True),
        ),
        migrations.AlterField(
            model_name='assistancelisting',
            name='audits',
            field=models.JSONField(help_text='Audits (112)'),
        ),
        migrations.AlterField(
            model_name='assistancelisting',
            name='authorization',
            field=models.JSONField(help_text='Authorization (040)'),
        ),
        migrations.AlterField(
            model_name='assistancelisting',
            name='credentials_documentation',
            field=models.JSONField(help_text='Credentials/Documentation (083)'),
        ),
        migrations.AlterField(
            model_name='assistancelisting',
            name='deadlines',
            field=models.JSONField(help_text='Deadlines (094)'),
        ),
        migrations.AlterField(
            model_name='assistancelisting',
            name='preapplication_coordination',
            field=models.JSONField(help_text='Preapplication Coordination (091)'),
        ),
        migrations.AlterField(
            model_name='assistancelisting',
            name='program_accomplishments',
            field=models.JSONField(help_text='Program Accomplishments (130)'),
        ),
        migrations.AlterField(
            model_name='assistancelisting',
            name='regional_local_office',
            field=models.JSONField(help_text='Regional or Local Office (151)'),
        ),
        migrations.AlterField(
            model_name='assistancelisting',
            name='reports',
            field=models.JSONField(help_text='Reports (111)'),
        ),
        migrations.AlterField(
            model_name='assistancelisting',
            name='requirements',
            field=models.JSONField(help_text='Formula and Matching Requirements (101)'),
        ),
        migrations.AlterField(
            model_name='pdfextract',
            name='cap_text',
            field=models.JSONField(help_text='Extracted PDF corrective action plan'),
        ),
        migrations.AlterField(
            model_name='pdfextract',
            name='finding_text',
            field=models.JSONField(help_text='Extracted PDF finding'),
        ),
    ]
