# Generated by Django 3.1 on 2020-08-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_auto_20200812_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfda',
            name='cfda_program_name',
            field=models.CharField(blank=True, help_text='Name of Federal Program (auto-generated by FAC from the CFDA catalog)', max_length=300, null=True),
        ),
    ]
