# Generated by Django 3.0.3 on 2020-02-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('report_id', models.CharField(max_length=8)),
                ('audit_year', models.DecimalField(decimal_places=0, help_text='Audit Year and DBKEY (database key) combined make up the primary key.', max_digits=4)),
                ('dbkey', models.CharField(help_text='Audit Year and DBKEY (database key) combined make up the primary key.', max_length=6)),
                ('ein', models.CharField(help_text='Employer Identification Number', max_length=9)),
                ('fy_end_date', models.DateField()),
                ('fac_accepted_date', models.DateField()),
                ('date_received', models.DateField()),
                ('file_type', models.CharField(choices=[('form', 'form'), ('audit', 'audit')], max_length=8)),
                ('file_name', models.CharField(max_length=32)),
            ],
        ),
    ]
