# Generated by Django 3.0.3 on 2020-02-11 18:50

import compositefk.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20200204_1839'),
        ('fac_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facdocument',
            name='audit',
            field=compositefk.fields.CompositeForeignKey(default=None, null_if_equal=[], on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='data.Audit', to_fields={'audit_year': compositefk.fields.LocalFieldValue('audit_year'), 'dbkey': compositefk.fields.LocalFieldValue('dbkey')}),
            preserve_default=False,
        ),
    ]
