# Generated by Django 3.1 on 2020-10-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac_scraper', '0004_auto_20200220_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facdocument',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='facdocument',
            name='ein',
        ),
        migrations.RemoveField(
            model_name='facdocument',
            name='fac_accepted_date',
        ),
        migrations.RemoveField(
            model_name='facdocument',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='facdocument',
            name='fy_end_date',
        ),
        migrations.RemoveField(
            model_name='facdocument',
            name='report_id',
        ),
    ]
