# Generated by Django 3.1 on 2020-10-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac_scraper', '0005_auto_20201019_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='facdocument',
            name='file_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
